check windows  paths

diff --git a/.github/workflows/build_wheel.yml b/.github/workflows/build_wheel.yml
--- a/.github/workflows/build_wheel.yml
+++ b/.github/workflows/build_wheel.yml
@@ -16,7 +16,8 @@ jobs:
       max-parallel: 4
       fail-fast: false
       matrix:
-        platform: [ubuntu-latest, windows-latest]
+        # platform: [ubuntu-latest, windows-latest]
+        platform: [windows-latest]
         python-version: ["3.10"]
         # cuda-version: ["12.4.0"]
         # fix due to missing 12.4.0 in the network
@@ -29,6 +30,30 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: recursive
+
+      - name: Set CUDA paths for Windows
+        if: runner.os == 'Windows'
+        run: |
+          echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin;${env:PATH}" >> $env:GITHUB_ENV
+          echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" >> $env:GITHUB_ENV
+          echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" >> $env:GITHUB_ENV
+
+      # check ENV variable
+      - name: Check CUDA paths
+        if: runner.os == 'Windows'
+        run: |
+          echo "PATH:"
+          echo $env:PATH
+          echo "CUDA_PATH:"
+          echo $env:CUDA_PATH
+          echo "CUDA_HOME:"
+          echo $env:CUDA_HOME
+
+      # throw error
+      - name: throw error
+        run: |
+          echo "throw error"
+          exit 1
 
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
